"""Added tasks

Revision ID: 7ca21ed6e4ab
Revises: 
Create Date: 2024-08-20 16:19:04.599479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca21ed6e4ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.Enum('CSV', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSING', 'DONE', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('file_input_path', sa.String(length=255), nullable=False),
    sa.Column('file_output_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
