"""Added timestamp

Revision ID: 8f9dd2b0b560
Revises: 7ca21ed6e4ab
Create Date: 2024-08-20 19:11:29.950090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9dd2b0b560'
down_revision = '7ca21ed6e4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_stamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('time_stamp')

    # ### end Alembic commands ###
